name: Narmeen Haq Photography
favicon: null
layout_spectrum: 0.26293
typography_spectrum: 0.8247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b6b6b6'
    - '#949494'
    - '#434343'
    - '#616161'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
